<?php

namespace App\Tests\Integration\Ui\Rest\Controller\User;

use App\Tests\Integration\Infrastructure\Core\BaseApiTest;

final class UserRegisterTest extends BaseApiTest
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     */
    public function it_create_user()
    {
        $firstName = 'username';
        $lastName = 'lastname';
        $email = 'useremail@emauil.com';

        $client = $this->createAuthenticatedClient();

        $client->request(
            'POST',
            '/api/register',
            [
                'firstName' => $firstName,
                'lastName' => $lastName,
                'email' => $email,
                'password' => 'password'
            ],
        );

        $response = $client->getResponse();
        $this->assertOkResponseStatus($response);
        $data = json_decode($response->getContent(), true);
        $userId = $data['userId'];

        $client->request(
            'GET',
            '/api/user/'. $userId,
        );

        $response = $client->getResponse();
        $this->assertOkResponseStatus($response);

        $data = json_decode($response->getContent(), true);

        $this->assertEquals($userId, $data['id']);
        $this->assertEquals($firstName, $data['firstName']);
        $this->assertEquals($lastName, $data['lastName']);
        $this->assertEquals($email, $data['email']);
    }

    /**
     * @test
     */
    public function it_not_create_user_when_email_is_used()
    {
        $client = static::createClient();
        $client->request(
            'POST',
            '/api/register',
            [
                'firstName' => 'user2',
                'lastName' => 'user2',
                'email' => 'useremail@emauil.com',
                'password' => 'murawskimat'
            ],
        );

        $response = $client->getResponse();
        $this->assertBadRequestResponseStatus($response);
    }
}
