services:

    _defaults:
      autowire: true
      autoconfigure: true
      public: false

    App\Ui\Rest\Controller\:
      resource: '../../Controller'
      tags: ['controller.service_arguments']
